name: Build and Test app
on: [push, pull_request]
jobs:
  publish:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push Stytch_framework/Stytch.podspec
        
  build:
    runs-on: macos-latest
    env:
      XC_VERSION: ${{ '11.4' }}
      XC_WORKSPACE: ${{ 'Stytch.xcworkspace' }}
      XC_SCHEME: ${{ 'Stytch' }}
    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v2
    - name: Run Unit and UI Tests
      run: /usr/bin/xcodebuild test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'
  
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer



name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push Stytch.podspec
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push Stytch.podspec
        
  deploy:
    - name: Publish Slack Message
      env:
        SLACK_WEBHOOK: ${{ secrets.PROD_SLACK_WEBHOOK }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{
          "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "<https://github.com/stytchauth/web|web> just deployed <https://github.com/stytchauth/web/commit/${{github.event.inputs.sha}}|${{steps.calculate-short-sha.outputs.SHORT_SHA}}> into prod"
              }
            }
          ]
        }' $SLACK_WEBHOOK
