name: Test and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  test_and_deploy:
    runs-on: macos-latest

    env:
      XC_VERSION: ${{ '14.2' }}
      XCodeProj: ${{ 'Stytch.xcodeproj' }}
      XC_SCHEME: ${{ 'StytchTests' }}
    steps:
    - uses: actions/checkout@v2
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        xcodebuild test -project "$XCodeProj" -scheme "$XC_SCHEME" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11,OS=14.4"
    
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push Stytch.podspec
